spring.data.elasticsearch.clusterName: elasticsearch
spring.data.elasticsearch.clusterNodes: localhost:9200
server.port: 8090
--- ###########################################################################

spring.profiles: integration

--- ###########################################################################

spring.profiles: local

--- ###########################################################################

spring.profiles: staging

--- ###########################################################################

spring.profiles: prod
